id: I700BAE05
legacy_id: P007861
ocr_import_info:
  bdrc_scan_id: W10305
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T00:01:21'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:54:07.128988+00:00'
last_modified: 2022-08-29 20:58:33.771583
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W10305
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW10305
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས།
  author: ས་སྐྱ་ཡོངས་འཛིན་ངག་དབང་ཆོས་གྲགས།
statistics:
  ocr_word_mean_confidence_index: 0.9565299124595404
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2141:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2141
      total_pages: 518
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2141.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9568674006330706
    legacy_id: v002
  I2143:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2143
      total_pages: 580
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2143.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9598084422592708
    legacy_id: v004
  I2140:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2140
      total_pages: 516
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2140.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9599627164237613
    legacy_id: v001
  I2144:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2144
      total_pages: 488
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2144.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9639594644102365
    legacy_id: v005
  I2145:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2145
      total_pages: 568
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I2145.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9657042238317554
    legacy_id: v006
  I2142:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2142
      total_pages: 624
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2142.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9363238699483992
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
