id: I700BAE05
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T00:05:58+00:00'
last_modified: '2022-06-09T06:43:12.138723+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W10305
  title: གསུང་འབུམ། ངག་དབང་ཆོས་གྲགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A1F9:
      image_group_id: I2140
      title: ''
      total_pages: 516
      order: 1
      base_file: A1F9.txt
    AFCB:
      image_group_id: I2141
      title: ''
      total_pages: 518
      order: 2
      base_file: AFCB.txt
    F531:
      image_group_id: I2142
      title: ''
      total_pages: 624
      order: 3
      base_file: F531.txt
    9F35:
      image_group_id: I2143
      title: ''
      total_pages: 580
      order: 4
      base_file: 9F35.txt
    B30A:
      image_group_id: I2144
      title: ''
      total_pages: 488
      order: 5
      base_file: B30A.txt
    66B4:
      image_group_id: I2145
      title: ''
      total_pages: 568
      order: 6
      base_file: 66B4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
